CREATE TABLE MYUSER.Info_Centr (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch CHAR(3)
    batch_date VARCHAR(10),
    batch_time VARCHAR(8),
    batch_sla VARCHAR(8)
);
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-01', '03:41:17', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-02', '19:37:42', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-03', '22:58:05', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-04', '10:42:33', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-05', '09:56:51', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-06', '13:28:19', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-07', '17:25:28', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-08', '22:50:07', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-09', '15:07:44', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-10', '08:15:36', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-11', '00:25:12', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-12', '00:29:59', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-13', '20:21:24', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-14', '23:46:11', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-15', '04:41:38', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-16', '12:09:47', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-17', '07:36:22', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-18', '14:50:53', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-19', '21:10:09', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-20', '03:01:30', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-21', '22:47:14', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-22', '15:28:45', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-23', '05:12:26', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-24', '06:57:39', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-25', '14:13:16', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-26', '15:15:48', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-27', '14:56:03', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-28', '01:03:29', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-29', '16:28:41', '21:00:00');
INSERT INTO INFO_DFO (batch_name, batch_date, batch_time, batch_sla) VALUES ('ДФО', '2025-06-30', '22:43:55', '21:00:00');